"""Model-domain rejection is typed, transactional, and Pareto-ineligible.

Only small synthetic fixtures are evaluated; persisted production handoffs
and successful runs are never regenerated by these tests.
"""
from __future__ import annotations

import csv
import json
import pickle
from types import SimpleNamespace

import numpy as np
import pytest
import torch

from ecsp_nsga2.geometry import RasterizedGeometry
from ecsp_nsga2.nsga2 import Individual
from ecsp_nsga2.propagation import (
    ConfiguredModelTemperatureRangeExceeded as RangeError,
    PropagationCandidateModelValidityError,
    PropagationCandidateNumericalError,
    candidate_failure_payload,
)
from ecsp_nsga2 import workflow as workflow_module
from ecsp_nsga2.workflow import NSGA2ElectricalSolidWorkflow as Workflow
from ecsp_reactive.condensed import BCReactiveHandoffAdapter, BCReactiveSolver
from ecsp_reactive.condensed.tensor_math import (
    LOCAL_CHEMISTRY_DIAGNOSTIC_NAMES, TensorCondensedKernel,
)
from ecsp_reactive.condensed.tensor_solver import run_tensor_solvers
from ecsp_reactive.condensed.validation_cases import synthetic_condensed_case
from test_reactive_tensor_backend import scalar_local_kwargs


def model_case(temperature=2500.0, duration=1.0e-3):
    handoff, propagation, bc, reactive = synthetic_condensed_case(
        shape=(5, 5), rates=(2.0, 1.0), heats=(1000.0, 2000.0),
        alpha=(0.1, 0.2),
    )
    handoff["temperatureAtOnset_K"][:] = min(temperature, 2490.0)
    handoff["temperatureAtOnset_K"][1, 2] = temperature
    bc["thermal"]["maximumTemperature_K"] = 2500.0
    propagation.update(duration_s=duration, time_step_s=duration,
                       snapshot_interval_s=duration)
    reactive.update(chemistry_integration_mode="local_adaptive_thermochemical",
                    stationary_mechanics_fast_path=True, riemann_solver="hllc")
    adapted = BCReactiveHandoffAdapter(propagation, bc, reactive).adapt(handoff)
    return BCReactiveSolver(adapted, propagation, bc, reactive,
                            initialize_electrical=False)


@pytest.mark.parametrize("temperature,dt,valid", [
    (2499.0, 1.0e-3, True),
    (2500.0, 0.0, True),
    (2500.0, 5.0e-11, True),  # Positive overshoot inside the ORIGINAL allowance.
    (2500.0, 1.0e-3, False),
])
def test_unchanged_temperature_boundary_numpy_torch(temperature, dt, valid):
    solver = model_case(temperature)
    before = solver.U.copy()
    kernel = TensorCondensedKernel([solver], "cpu")
    tensor_after, tensor_valid, row = kernel.advance_local(
        kernel.initial, kernel.tensor([dt]))
    diagnostics = dict(zip(LOCAL_CHEMISTRY_DIAGNOSTIC_NAMES, row[0].tolist()))
    assert bool(tensor_valid[0]) is valid
    if valid:
        after, _ = solver.chem.advance_local(
            solver.U, solver.thermo, dt, **scalar_local_kwargs(solver))
        np.testing.assert_allclose(tensor_after[0].numpy(), after, rtol=2e-15, atol=1e-10)
        assert diagnostics[RangeError.code] == 0.0
        if dt == 5.0e-11:
            final_t = solver.thermo.primitive(after)[..., 3].max()
            assert 2500.0 < final_t <= 2500.0 + 256*np.finfo(float).eps*final_t
    else:
        with pytest.raises(RangeError) as captured:
            solver.chem.advance_local(
                solver.U, solver.thermo, dt, **scalar_local_kwargs(solver))
        error = captured.value
        assert isinstance(error, PropagationCandidateModelValidityError)
        assert not isinstance(error, PropagationCandidateNumericalError)
        assert error.cell_index == 7  # Original (1, 2), not a compacted index.
        assert diagnostics[RangeError.code] == 1.0
        assert diagnostics["offending_temperature_cell_index"] == 7
        assert diagnostics["observed_maximum_temperature_K"] == pytest.approx(
            error.observed_maximum, abs=1e-12)
        assert error.observed_maximum > 2500.0 + error.roundoff_tolerance
        np.testing.assert_array_equal(tensor_after[0].numpy(), before)
    np.testing.assert_array_equal(solver.U, before)
    np.testing.assert_array_equal(kernel.initial[0].numpy(), before)


def test_valid_numpy_and_torch_retain_exact_prepatch_golden_state():
    solver = model_case(300.0)
    expected_cell = np.asarray([
        1000.0, 0.0, 0.0, 4270000.0, 200.0, 250.0,
        113.58333333333334, 113.58333333333334, 50.0,
        78.33333333333334, 43.33333333333333, 0.0,
    ])
    after, _ = solver.chem.advance_local(
        solver.U, solver.thermo, 0.05, **scalar_local_kwargs(solver))
    kernel = TensorCondensedKernel([solver], "cpu")
    tensor_after, valid, _ = kernel.advance_local(kernel.initial, kernel.tensor([0.05]))
    assert bool(valid[0])
    expected = np.broadcast_to(expected_cell, solver.U.shape)
    np.testing.assert_array_equal(after, expected)
    np.testing.assert_array_equal(tensor_after[0].numpy(), expected)


def test_range_error_cpu_worker_pickle_and_numerical_failure_remain_distinct():
    error = RangeError(2500.0, 2500.0012922586584, 32337, 1.4210862060842023e-10)
    recovered = pickle.loads(pickle.dumps(error))
    assert type(recovered) is RangeError
    assert str(recovered) == str(error)
    metrics = candidate_failure_payload(recovered)
    assert metrics["propagationSucceeded"] is False
    assert metrics["postOnsetModelValid"] is False
    assert metrics["postOnsetValidityConstraintViolation"] == 1.0
    assert metrics["postOnsetValidityReason"] == RangeError.code
    assert metrics["offendingCellIndex"] == 32337
    json.dumps(metrics, allow_nan=False)
    numerical = PropagationCandidateNumericalError(RangeError.code)
    assert candidate_failure_payload(numerical) == {
        "status": "failed", "errorType": "PropagationCandidateNumericalError",
        "message": RangeError.code,
    }  # Even identical text cannot create a validity classification.


@pytest.mark.parametrize("half", [1, 2])
def test_scalar_range_rejection_rolls_back_whole_trial(tmp_path, monkeypatch, half):
    solver = model_case(300.0)
    before = solver.U.copy()
    original = solver._chemistry_half_step
    calls = []
    checkpoints = []

    def chemistry(state, dt):
        calls.append(state.copy())
        if len(calls) == half:
            raise RangeError(2500, 2500.001, 7, 1.42e-10)
        return original(state, dt)

    monkeypatch.setattr(solver, "_chemistry_half_step", chemistry)
    monkeypatch.setattr(solver, "_restore_electrical_checkpoint", checkpoints.append)
    with pytest.raises(RangeError):
        solver.run(tmp_path)
    assert len(calls) == half  # No timestep retry.
    assert len(checkpoints) == 1
    assert solver.step_number == 0
    assert solver.rejected_steps == 1
    np.testing.assert_array_equal(solver.U, before)
    with np.load(tmp_path / "INCOMPLETE_STATE.npz") as saved:
        np.testing.assert_array_equal(saved["U"], before)
        assert saved["time_after_onset_s"] == 0
    assert not (tmp_path / "propagation_metrics.json").exists()
    metrics = json.loads((tmp_path / "PROPAGATION_FAILED.json").read_text())
    assert metrics["failureCode"] == RangeError.code


def test_tensor_range_failure_is_lane_local_and_success_unchanged(tmp_path):
    failed, valid, reference = model_case(), model_case(300), model_case(300)
    before = failed.U.copy()
    results = run_tensor_solvers([failed, valid], [tmp_path / "bad", tmp_path / "good"],
                                {"backend": "torch_batch"})
    baseline = run_tensor_solvers([reference], [tmp_path / "reference"],
                                 {"backend": "torch_batch"})[0]
    assert isinstance(results[0], RangeError)
    assert results[0].cell_index == 7
    assert results[1]["status"] == "complete"
    assert results[1]["postOnsetModelValid"] is True
    assert failed.step_number == 0
    np.testing.assert_array_equal(failed.U, before)
    np.testing.assert_array_equal(valid.U, reference.U)
    for key in ("finalUnreactedAreaFraction", "establishedTimeAfterOnset_s",
                "meanEffectiveRegressionVelocity_m_per_s", "reactionFrontNonuniformity"):
        assert results[1][key] == baseline[key]
    saved = json.loads((tmp_path / "bad" / "PROPAGATION_FAILED.json").read_text())
    assert saved["postOnsetValidityReason"] == RangeError.code


def workflow_fixture(monkeypatch, results):
    candidates = [Individual(name, {}, np.asarray([0.1, 0.2, 0.3, 0.4]))
                  for name in results]
    raster = RasterizedGeometry(np.zeros((5, 5), bool), np.zeros((5, 5), bool),
                                {}, 0.0, {})
    monkeypatch.setattr(workflow_module, "rasterize_and_validate", lambda *_: raster)
    handoff = {"handoff": {"onsetSucceeded": True}}
    fake = SimpleNamespace(
        evaluator=SimpleNamespace(config={"bcGlobal": {"probe": True}},
            evaluate_handoff_batch=lambda payloads: [handoff for _ in payloads]),
        post_onset_cfg={"backend": "reactive_euler", "compare_backends": False},
        propagation_cfg={}, limits=None,
        _select_propagation_candidates=lambda *_: candidates,
        _propagation_metadata=lambda ind, raster, **kwargs: {"geometry_id": ind.geometry_id},
        _validate_handoff_reevaluation=lambda *_: {"preflameHandoffReevaluationConsistent": True},
        _write_population_csv=Workflow._write_population_csv,
        _copy_recommendation_geometry=lambda *_: None,
        _evaluate_area_matched_staggered=lambda *_, **__: None,
    )
    fake._run_propagation_refinement = lambda ind, raster, output, precomputed_result=None, **kwargs: (
        Workflow._run_propagation_refinement(
            fake, ind, raster, output, precomputed_result=results[ind.geometry_id], **kwargs))
    return fake, candidates


def complete_metrics():
    return dict(status="complete", onsetSucceeded=True,
                finalUnreactedAreaFraction=0.5, establishedTimeAfterOnset_s=0.01,
                meanEffectiveRegressionVelocity_m_per_s=0.1, reactionFrontNonuniformity=0.2)


def read_csv(path):
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


@pytest.mark.parametrize("all_invalid", [False, True])
def test_workflow_filters_validity_before_pareto_and_retains_audit(
        tmp_path, monkeypatch, all_invalid):
    results = {"range": RangeError(2500, 2500.001, 7, 1.42e-10),
               "numerical": PropagationCandidateNumericalError("work budget")}
    if not all_invalid:
        results["valid"] = complete_metrics()
    fake, candidates = workflow_fixture(monkeypatch, results)
    original_pareto = workflow_module.pareto_front
    pareto_inputs = []

    def inspect_pareto(population):
        pareto_inputs.append([ind.geometry_id for ind in population])
        return original_pareto(population)

    monkeypatch.setattr(workflow_module, "pareto_front", inspect_pareto)
    if all_invalid:
        with pytest.raises(RuntimeError, match="failed post-onset"):
            Workflow._finalise_with_propagation(fake, candidates, candidates, tmp_path)
        assert not (tmp_path / "recommended_design.json").exists()
        assert pareto_inputs == [[]]
    else:
        recommendation = Workflow._finalise_with_propagation(fake, candidates, candidates, tmp_path)
        assert recommendation.geometry_id == "valid"
        assert pareto_inputs == [["valid"]]  # Explicit exclusion, not penalty-based ranking.
        for filename in ("final_pareto_designs.csv", "recommended_design_metrics.csv"):
            assert [row["geometry_id"] for row in read_csv(tmp_path / filename)] == ["valid"]
        assert json.loads((tmp_path / "recommended_design.json").read_text())["geometry_id"] == "valid"
    audit = {row["geometry_id"]: row for row in read_csv(tmp_path / "all_propagation_refined_designs.csv")}
    assert set(audit) == set(results)
    assert audit["range"]["postOnsetModelValid"] == "False"
    assert audit["range"]["postOnsetValidityReason"] == RangeError.code
    assert audit["range"]["onsetSucceeded"] == "True"
    assert audit["range"]["constraint_violation"] == "1.0"
    assert audit["numerical"]["status"] == "propagation_failed"
    assert audit["numerical"]["constraint_violation"] == "100.0"
    assert audit["numerical"]["postOnsetValidityReason"] == ""
    for ind in candidates:
        assert ind.constraint_violation == 0.0
        assert "postOnsetModelValid" not in ind.metrics
        np.testing.assert_array_equal(ind.objectives, [0.1, 0.2, 0.3, 0.4])


def test_post_onset_writer_preserves_typed_failure(tmp_path, monkeypatch):
    from ecsp_nsga2.post_onset import run_post_onset
    from ecsp_reactive.condensed import solver as solver_module
    h, p, b, r = synthetic_condensed_case(shape=(5, 5))

    def reject(*args, **kwargs):
        raise RangeError(2500, 2500.001, 7, 1.42e-10)

    monkeypatch.setattr(solver_module, "run_reactive_propagation", reject)
    with pytest.raises(RangeError):
        run_post_onset(h, p, b, tmp_path,
                      post_onset_config={"backend": "reactive_euler", "reactive_euler": r})
    data = json.loads((tmp_path / "reactive_euler" / "PROPAGATION_FAILED.json").read_text())
    assert data["failureCode"] == RangeError.code
    assert data["observedMaximumTemperature_K"] == 2500.001


@pytest.mark.parametrize("backend", ["numpy", "torch"])
def test_other_endpoint_failure_is_not_hidden_by_temperature_range(monkeypatch, backend):
    from ecsp_reactive.condensed.chemistry import PVA
    solver = model_case()
    solver.U[..., PVA] = 1.0
    kernel = TensorCondensedKernel([solver], "cpu")
    owner = solver.chem if backend == "numpy" else kernel
    original = owner._solve_local_cells

    def overconsume(*args, **kwargs):
        solved = original(*args, **kwargs)
        # Deliberately invalid numerical output: both a negative inventory and
        # an over-temperature endpoint. Never reinterpret it as validity-only.
        solved["alpha"][7] = args[0][7] + 0.1
        return solved

    monkeypatch.setattr(owner, "_solve_local_cells", overconsume)
    if backend == "numpy":
        with pytest.raises(PropagationCandidateNumericalError, match="Nonphysical local"):
            solver.chem.advance_local(solver.U, solver.thermo, 0.001,
                                      **scalar_local_kwargs(solver))
    else:
        after, valid, row = kernel.advance_local(kernel.initial, kernel.tensor([0.001]))
        assert not bool(valid[0])
        field = LOCAL_CHEMISTRY_DIAGNOSTIC_NAMES.index(RangeError.code)
        assert row[0, field] == 0
        np.testing.assert_array_equal(after[0].numpy(), solver.U)


def test_tensor_second_half_range_failure_retains_accepted_state():
    solver = model_case(2499.999)
    kernel = TensorCondensedKernel([solver], "cpu")
    after, _, _, _, valid = kernel.trial(kernel.initial, kernel.tensor([0.001]), False)
    field = LOCAL_CHEMISTRY_DIAGNOSTIC_NAMES.index(RangeError.code)
    assert kernel.trial_local_diagnostics[0, 0, field] == 0
    assert kernel.trial_local_diagnostics[0, 1, field] == 1
    assert kernel.trial_failure_reason[0] == 4
    assert not bool(valid[0])
    np.testing.assert_array_equal(after[0].numpy(), solver.U)


@pytest.mark.parametrize("backend", ["numpy_cpu", "torch_batch"])
def test_batch_dispatch_preserves_structured_validity_error(tmp_path, backend):
    from ecsp_nsga2.post_onset_batch import run_post_onset_batch
    h, p, b, r = synthetic_condensed_case(shape=(5, 5))
    h["temperatureAtOnset_K"][1, 2] = 2500.0
    before = h["temperatureAtOnset_K"].copy()
    b["thermal"]["maximumTemperature_K"] = 2500.0
    p.update(duration_s=0.001, time_step_s=0.001, snapshot_interval_s=0.001)
    r.update(chemistry_integration_mode="local_adaptive_thermochemical")
    results = run_post_onset_batch(
        [h], p, b, [tmp_path], post_onset_config={
            "backend": "reactive_euler", "reactive_euler": r,
            "execution": {"backend": backend, "device": "cpu", "batch_size": 1,
                          "cpu_budget": 4, "host_reserve": 2, "cpu_workers": 1},
        })
    assert isinstance(results[0], RangeError)
    assert results[0].cell_index == 7
    np.testing.assert_array_equal(h["temperatureAtOnset_K"], before)
    data = json.loads((tmp_path / "reactive_euler" / "PROPAGATION_FAILED.json").read_text())
    assert data["failureCode"] == RangeError.code
    assert data["postOnsetModelValid"] is False
    assert data["offendingCellIndex"] == 7
